Add envvar support

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,12 +1,29 @@
 #!/usr/bin/env bash
+# bin/compile <build-dir> <cache-dir> <env-dir>
 
-set -e          # fail fast
-set -o pipefail # do not ignore exit codes when piping output
-#set -x          # enable debugging
+# Fail immediately on non-zero exit code.
+set -e
+# Fail immediately on non-zero exit code within a pipeline.
+set -o pipefail
+# Fail on undeclared variables.
+set -u
+# Debug, echo every command
+#set -x
 
+# parse and derive params
 BUILD_DIR="${1}"
 CACHE_DIR="${2}"
 ENV_DIR="${3}"
+BIN_DIR=$(cd $(dirname $0); pwd) # absolute path
+
+# source in common functions
+. "${BIN_DIR}/common.sh"
+
+export_env_dir "${ENV_DIR}"
+
+#create the cache dir if it doesn't exist
+mkdir -p "${CACHE_DIR}"
+
 JQ_DIR="${BUILD_DIR}/vendor/jq"
 PROFILED_DIR="${BUILD_DIR}/.profile.d"
 
@@ -15,11 +32,6 @@ if [[ -n ${JQ_BIN_URL:-} ]]; then
 else
 	JQ_BIN_URL="https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64"
 fi
-
-BP_DIR=$(cd "$(dirname "${0}")"; cd ..; pwd)
-
-# Load some convenience functions like status(), echo(), and indent()
-source "${BP_DIR}/bin/common.sh"
 
 mkdir -p "${JQ_DIR}/bin"
 
